env:
  browser: true
  es2020: true
extends:
  - 'plugin:@shopify/typescript'
  - 'plugin:@shopify/typescript-type-checking'
  - 'plugin:@shopify/react'
  - 'plugin:@shopify/prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  project: './packages/**/tsconfig.json'
plugins:
  - '@typescript-eslint'
rules: {}
